### ISSUE TITLE
Allow for disabling the outline padding

### ISSUE THREAD

**Issue by tfrommen** [kalimahapps/Editor-Block-Outline#2]
Hi there,

First of all, thank you for this brilliant plugin!

Now, I would like to request that the setting for the padding, which will be added to any block no matter what, can be disabled, for example, via a filter in PHP.

The reason being that setting a fixed padding for all blocks will eventually mess with blocks that have a padding set, especially if there are varying padding values across blocks. This can be nested blocks, or different types of blocks that have padding according to where they are placed in a grid-based theme etc.

Ideally, as a developer, you get to decide if outline padding should be available or not (the default being `true` to keep the current behavior), and then ensure that the control in the plugin sidebar shows (or does not show), and the CSS custom property and padding is either being defined, or not.

Does that make sense?
I'm happy to provide a PR, but for that I would need to know how you would like to implement this (and where).

Thanks,
Thorsten

**Comment by abdul-alhasany** [comment]
Hi @tfrommen 
Thanks for the feedback and apologies for the late response.

I agree with your assessment that padding should not be added for every block. I think the best way to approach it is to add a switch button next to the padding option to toggle padding option. This way the user would have the control over the UI rather than the developer which the intent of the plugin.

You are more than welcome to submit a PR. I will try to fix this in the next couple of weeks if I have time.

Thanks for the question, and I would appreciate if you rate the plugin on WordPress website as well.

**Comment by tfrommen** [comment]
Hi @kalimah-apps!

> I think the best way to approach it is to add a switch button next to the padding option to toggle padding option. This way the user would have the control over the UI rather than the developer which the intent of the plugin.

This sounds like a good option to me.
However, it would be good to start out with no padding, by default. So, my suggestion here is that the toggle would default to checked only if a padding has been specified before (and is stored for the current user). This means that on a fresh install, all users would not have a custom padding set by default, but they can opt in to this.

How does that sound?

> I would appreciate if you rate the plugin on WordPress website as well.

I'll see what I can do. 🙂

**Comment by tfrommen** [comment]
Hi @kalimah-apps - I created a PR with a first pass for this: #3.
When you have some time, can you please take a look at the approach, and try it out yourself?
Thanks!

**Comment by abdul-alhasany** [comment]
@tfrommen 
Thanks for PR. I merged it into master and update the plugin on WordPress directory. It seems the version number is not changing. I guess it needs sometime to update.

**Comment by tfrommen** [comment]
That's awesome, thanks!

I didn't update the version number in the main plugin file, so I guess this is where that's coming from.

**Comment by abdul-alhasany** [comment]
You are right. I updated the version number. The new update is available for download. Thanks for the contribution.
