### ISSUE TITLE
Outlines on hover

### ISSUE THREAD

**Issue by davidmpurdy** [kalimahapps/Editor-Block-Outline#5]
What do you think about a feature to show the block hierarchy structure on hover? I've been experimenting with some very simple editor CSS to show outlines (no block labels/names or anything) of every block and its children on hover. 

Essentially (I'm sure there's a better way to do this): 

```
.wp-block:hover .wp-block, 
.wp-block:hover {
    border: 1px dashed #999;
}
```

The effect is that an editor can quickly scan the structure of a section by hovering over it, which seems to make it easier to select the block they want to edit, especially with the block name turned on in the plugin. 

Would you be open to a PR for this feature (maybe disabled by default with a switch to turn it on)?

**Comment by abdul-alhasany** [comment]
In the current plugin settings you can set display outline to "always" which shows all the block outlines at once. Is that something close to your suggestion? 

Also, you can click on the list icon at the top of the editor to see the hierarchy of the post.
