### ISSUE TITLE
Assets are enqueued in the frontend of the site, not just the editor.

### ISSUE THREAD

**Issue by Sephsekla** [kalimahapps/Editor-Block-Outline#7]
Testing a site on WordPress 6.5.5, I've noticed that the scripts and styles for the plugin are being loaded both in the editor and the frontend of the site, when these should only be needed within the editor.

I think that fixing this should be straightforward, swapping out

```php
add_action( 'enqueue_block_assets', array( $this, 'add_editor_assets' ) );
add_action( 'enqueue_block_assets', array( $this, 'add_init_scripts' ) );
```

for

```php
add_action( 'enqueue_editor_block_assets', array( $this, 'add_editor_assets' ) );
add_action( 'enqueue_editor_block_assets', array( $this, 'add_init_scripts' ) );
```

in outline.php would restrict these files to only load within the editor.

Happy to create a PR to address this if that solution makes sense, or is there anything here that does need to be loaded in the frontend?

**Comment by abdul-alhasany** [comment]
I don't think there is a need to load any assets to frontend. PR is welcome.

**Comment by Sephsekla** [comment]
Thanks @abdul-alhasany , I've created the PR at https://github.com/kalimahapps/Editor-Block-Outline/pull/8.
